FROM python:3.11

RUN pip install openai pyTelegramBotAPI

RUN pip install --force-reinstall "faster-whisper @ https://github.com/SYSTRAN/faster-whisper/archive/refs/heads/master.tar.gz"

WORKDIR /simple_openai_bot

COPY src/* /simple_openai_bot/

COPY text/* /simple_openai_bot/text/

RUN mkdir /simple_openai_bot/user_data

CMD python main.py
