FROM python:3.11

RUN pip install faster-whisper openai pyTelegramBotAPI

WORKDIR /simple_openai_bot

COPY src/* /simple_openai_bot/

COPY text/* /simple_openai_bot/text/

RUN mkdir /simple_openai_bot/user_data

CMD python main.py
