FROM python:3.11

RUN pip install openai==0.28.0 faster_whisper pyTelegramBotAPI

WORKDIR /simple_openai_bot

COPY src/* /simple_openai_bot/

COPY text/* /simple_openai_bot/text/

RUN mkdir /simple_openai_bot/user_data

CMD python main.py
